### ISSUE TITLE
Number of RAW files

### ISSUE THREAD

**Issue by bioinf-dev** [zrolfs/MetaMorpheus#104]
Hi, 
I am trying to use the software, and I seem to have a problem running multiple RAW files together. Should it be possible using the software? I succeeded running each RAW file separately.

Thanks
Ronen

**Comment by zrolfs** [comment]
Hi Ronen,
I'll look into it today and let you know. Do you have any more information on the issue you're observing? Is there a crash or does the program get stuck on a particular task?

Zach

**Comment by bioinf-dev** [comment]
Hi Zach
Thanks for your quick respond.
I tried running multiple files a few weeks ago, and transferred to running each file separately.  Therefore, I don’t remember the error.
I can re-run it, after my current runs finish. If you think it should be possible to run multiple raw files based on your previous experience, then I will check again that the reason wasn’t something else.

Best,
Ronen

**Comment by zrolfs** [comment]
I tried this yesterday and I was able to get through all of the tasks, but found that it only wrote spliced results for a single file. I'm working on a fix and will have it released ASAP. Thanks for bringing this to my attention.

**Comment by zrolfs** [comment]
Hi Ronen,
I believe I fixed the problem and I was able to analyze two raw files in a single run. I'd really appreciate your feedback if you have a chance to try it out. You can download the updated version here: [https://github.com/zrolfs/MetaMorpheus/releases](https://github.com/zrolfs/MetaMorpheus/releases)

Thanks again for drawing my attention to this issue!
Zach

**Comment by bioinf-dev** [comment]
Thanks Zach,
I currently started a run with the new version, and will update when it finishes.

Ronen

**Comment by bioinf-dev** [comment]
OK, I ran it twice with different files.
It is not working:

Run failed, Exception: Could not find file 'C:2020-04-03-21-41-18\2020-04-05_01-21-34\2020-04-05_01-21-34_QEP2_10348_YSA_MD55A3-IFN-1-500-HLA-I_1_311019-calib_FusionDatabaseAppendixTS.fasta'.

**Comment by zrolfs** [comment]
Thanks for your patience. I was able to run the updated version on several of my files without issue. However, I did get a crash when using a raw file that yielded no identifications and I'm currently working on a fix for that case. It threw a different error message than yours, though.

Would you be willing to share one of the MS files that caused the crash? It would greatly help me with debugging. I'd also need the database and which parameters you changed (if any). You can e-mail me at zrolfs@wisc.edu.

**Comment by zrolfs** [comment]
Hi Ronen,
Thank you for sharing the files with me. I was able to reproduce the issue and I believe this is now fixed in the new release, v0.1.2. I'm running through your data with the new version and I'll let you know if I make it all the way through.

**Comment by zrolfs** [comment]
> Hi Zach
> The run with multiple MS files finished. It is OK now. I received a separate output file for each of the MS files. 

>Thanks!
>Ronen

**Comment by zrolfs** [comment]
Fixed in v0.1.3
